### ISSUE TITLE
i have a problem  please help

### ISSUE THREAD

**Issue by speedand** [hanglearning/blockfl_implementation#1]
Step2. Now, worker will associate with a miner in its peer list and upload its updates to this miner.

After updating peer list, no peers are found in the network. System aborted. Please restart the node.

**Comment by hanglearning** [comment]
Hi, thanks for your interest in this project. Could you provide a series of actions for me to reproduce the issue? Have you followed my steps in this video https://www.youtube.com/watch?v=rL1S6vQn_wM&ab_channel=HangChen? 

Thanks.

**Comment by hanglearning** [comment]
See https://github.com/hanglearning/blockfl_implementation_incomplete/issues/2
