### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by speedand** [hanglearning/blockfl_implementation#2]
Miner is waiting for workers for 10 sections to upload their updates now...

Waiting 1...After updating peer list, no peers are found in the network. System aborted. Please restart the node

**Comment by hanglearning** [comment]
Hi, thanks for your interest in this project. Could you provide a series of actions for me to reproduce the issue? Have you followed my steps in this video https://www.youtube.com/watch?v=rL1S6vQn_wM&ab_channel=HangChen? When you start a second node or beyond, make sure to register with a node in the network, so the two nodes will be aware of each other and the registrant will copy the peer list from the registrar. If you start a second node or beyond by itself, it starts fresh and does not have any peer in its peer list.

**Comment by speedand** [comment]
<img width="1728" alt="截屏2023-04-17 10 47 32" src="https://user-images.githubusercontent.com/48684116/232367091-f92816e8-0c5a-493c-8339-5139bd119192.png">

Thank you for your reply. I run one miner and one worker.
I run 1 first, then run 2, and then 1 ends, which seems to be different from your video, 3 and 4 are the same.

**Comment by hanglearning** [comment]
No problem. I guess you are using the master branch? I may have made some changes to the master branch that breaks the code. Could you check out the dev branch and try again?

**Comment by speedand** [comment]
It was my oversight, thank you very much, I have solved this problem.

**Comment by hanglearning** [comment]
No problem! Glad it's resolved!
